import type { Template } from "@/types";

export const templates: Template[] = [
  // TikTok-style templates
  {
    id: "tt-capcut-1",
    name: "CapCut 3D Zoom",
    description: "Dramatic 3D zoom transition synced to beat drops. Great for before/after reveals.",
    thumbnail: "/templates/3d-zoom.jpg",
    category: "tiktok",
    tags: ["zoom", "3d", "transition", "viral"],
    duration: 15,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "text", startTime: 0, endTime: 15, x: 50, y: 10, width: 80, height: 20, content: "3D ZOOM", style: { fontSize: 48, color: "#fff", fontWeight: "bold" } },
    ],
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "tt-grwm-1",
    name: "GRWM Morning Vibe",
    description: "Get ready with me template with morning aesthetic, soft colors, and chill beats.",
    thumbnail: "/templates/grwm.jpg",
    category: "tiktok",
    tags: ["grwm", "aesthetic", "soft", "morning"],
    duration: 60,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "text", startTime: 0, endTime: 5, x: 50, y: 20, width: 80, height: 20, content: "6AM 💄", style: { fontSize: 36, color: "#fce7f3" } },
    ],
    createdAt: "2024-02-01T08:00:00Z",
  },
  {
    id: "tt-storytime-1",
    name: "Storytime Dramatic",
    description: "Dramatic zooms and captions for storytelling with maximum engagement.",
    thumbnail: "/templates/storytime.jpg",
    category: "tiktok",
    tags: ["storytime", "drama", "zoom", "engagement"],
    duration: 90,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "text", startTime: 0, endTime: 90, x: 50, y: 85, width: 90, height: 15, content: "POV: you finally snap", style: { fontSize: 24, color: "#fff", textShadow: "0 2px 4px #000" } },
    ],
    createdAt: "2024-03-10T12:00:00Z",
  },
  {
    id: "tt-transition-1",
    name: "Seamless Outfit Change",
    description: "Hidden cut transition perfect for outfit swaps and glow-ups.",
    thumbnail: "/templates/outfit-change.jpg",
    category: "tiktok",
    tags: ["transition", "outfit", "fashion", "glowup"],
    duration: 20,
    aspectRatio: "9:16",
    overlays: [],
    createdAt: "2024-01-22T10:30:00Z",
  },
  {
    id: "tt-asmr-1",
    name: "ASMR Packaging",
    description: "Soft triggers, gentle captions, and satisfying unboxing vibes.",
    thumbnail: "/templates/asmr.jpg",
    category: "tiktok",
    tags: ["asmr", "packaging", "satisfying", "soft"],
    duration: 45,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "text", startTime: 0, endTime: 45, x: 50, y: 10, width: 80, height: 20, content: "*crinkle*", style: { fontSize: 28, color: "#e5e7eb" } },
    ],
    createdAt: "2024-04-05T14:00:00Z",
  },

  // Brainrot templates
  {
    id: "br-sigma-1",
    name: "Sigma Grindset",
    description: "Explosive captions, bass-boosted audio, and motivational brainrot.",
    thumbnail: "/templates/sigma.jpg",
    category: "brainrot",
    tags: ["sigma", "grindset", "bass", "motivation"],
    duration: 30,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "text", startTime: 0, endTime: 30, x: 50, y: 15, width: 80, height: 20, content: "SIGMA", style: { fontSize: 64, color: "#ef4444", fontWeight: "900", textShadow: "0 0 20px #ef4444" } },
    ],
    createdAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "br-skibidi-1",
    name: "Skibidi Toilet Edit",
    description: "Chaotic brainrot with flashing lights and maximum absurdity.",
    thumbnail: "/templates/skibidi.jpg",
    category: "brainrot",
    tags: ["skibidi", "toilet", "chaos", "flash"],
    duration: 15,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "shape", startTime: 0, endTime: 15, x: 50, y: 50, width: 100, height: 100, style: { backgroundColor: "rgba(239,68,68,0.2)" } },
    ],
    createdAt: "2024-05-12T00:00:00Z",
  },
  {
    id: "br-gyatt-1",
    name: "Gyatt Detector",
    description: "Giant bold red text popping with every beat drop.",
    thumbnail: "/templates/gyatt.jpg",
    category: "brainrot",
    tags: ["gyatt", "bold", "red", "bass"],
    duration: 20,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "text", startTime: 0, endTime: 20, x: 50, y: 50, width: 80, height: 20, content: "GYATT", style: { fontSize: 80, color: "#dc2626", fontWeight: "900", textShadow: "0 4px 0px #000" } },
    ],
    createdAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "br-rizz-1",
    name: "Rizz Masterclass",
    description: "Smooth operator transitions with aura meters and pickup lines.",
    thumbnail: "/templates/rizz.jpg",
    category: "brainrot",
    tags: ["rizz", "aura", "smooth", "charisma"],
    duration: 25,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "text", startTime: 0, endTime: 25, x: 50, y: 10, width: 80, height: 20, content: "AURA: 999", style: { fontSize: 32, color: "#fbbf24", fontWeight: "bold" } },
    ],
    createdAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "br-mewing-1",
    name: "Mewing Tutorial",
    description: "Before/after facial restructuring with jawline measurements.",
    thumbnail: "/templates/mewing.jpg",
    category: "brainrot",
    tags: ["mewing", "jawline", "tutorial", "face"],
    duration: 40,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "shape", startTime: 0, endTime: 40, x: 25, y: 30, width: 10, height: 30, style: { backgroundColor: "rgba(34,197,94,0.3)" } },
    ],
    createdAt: "2024-07-01T00:00:00Z",
  },
  {
    id: "br-edge-core-1",
    name: "EdgeCore Glitch",
    description: "Maximum distortion, RGB split, chromatic aberration style.",
    thumbnail: "/templates/edgecore.jpg",
    category: "brainrot",
    tags: ["glitch", "edge", "rgb", "chaos"],
    duration: 18,
    aspectRatio: "9:16",
    overlays: [
      { id: "o1", type: "shape", startTime: 0, endTime: 18, x: 50, y: 50, width: 100, height: 100, style: { backgroundColor: "rgba(168,85,247,0.15)" } },
    ],
    createdAt: "2024-07-20T00:00:00Z",
  },
];
